#C\u00f3digo para pruebas locales
#spring.datasource.url=jdbc:mysql://localhost:3306/proyectointegrador?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=Tatu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

#JWT
jwt.secret=${SECRET}
jwt.expiration=3600

#Test
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.hibernate=DEBUG
